from kg_gen import KGGen
import dspy
from langchain_anthropic import ChatAnthropic
from langchain_core.messages import SystemMessage, HumanMessage
from llmkglitrev.prompts.system_prompts import extractor_prompt
from llmkglitrev.samples import sample_1

from llmkglitrev.samples.samples import sample_2, sample_3
from pydantic import BaseModel
import json
import litellm

import networkx as nx
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from collections import defaultdict
import os
litellm.enable_json_schema_validation = True

class KG_Generator:
    def __init__(self, model:str = "openai/gpt-4o"):
        if 'openai' in model:
            api_key = os.environ.get("OPENAI_API_KEY")
        if 
        
        self.kg = KGGen(
            model=model,  # Default model
            temperature=0.0,        # Default temperature
            api_key=os.environ.get("")  # Optional if set in environment or using a local model
        )
        self.extractor = ChatAnthropic(model_name="claude-sonnet-4-20250514", timeout=30, stop=None)
        self.extractor_system_prompt = SystemMessage(content=extractor_prompt)
        self.entities = []
        self.relations = []

    def _extract_scientific_content(self, text:str):
        response = self.extractor.invoke([
            self.extractor_system_prompt,
            HumanMessage(content=text)
        ])
        return json.loads(str(response.content))

    def generate(self, text: str):
        extracted_infor = self._extract_scientific_content(text)
        concept_graphs = {}
        for researcher, info in extracted_infor.items():
            publications = info.get("publications", [])
            expertise = info.get("expertise", [])
            ideas = info.get("idea", [])
            graphs = []

            for pub in publications:
                graph = self.kg.generate(pub)
                graphs.append(graph)

            combined_graph = self.kg.aggregate(graphs)
            print(combined_graph)
            concept_graphs.update({researcher:combined_graph})
        return concept_graphs

    def _fetch_graph(self, graph):

        # Create NetworkX graph
        G = nx.DiGraph()
        
        # Add nodes (entities)
        entities = graph.entities if hasattr(graph, 'entities') else set()
        for entity in entities:
            G.add_node(entity)
        
        # Add edges (relations)
        relations = graph.relations if hasattr(graph, 'relations') else set()
        for source, relation, target in relations:
            G.add_edge(source, target, label=relation)

        return G, entities, relations

    def visualize_graph(self, graph: nx.DiGraph, layout="spring", figsize=(12, 8), save_path=None):
        """
        Visualize the knowledge graph generated by the generate function.
        
        Args:
            graph: The Graph object returned by self.kg.generate()
            layout: Layout algorithm ('spring', 'circular', 'kamada_kawai', 'shell')
            figsize: Figure size as tuple (width, height)
            save_path: Optional path to save the visualization
        """
        
        G, entities, relations = self._fetch_graph(graph)

        # Set up the plot
        plt.figure(figsize=figsize)
        
        # Choose layout
        if layout == "spring":
            pos = nx.spring_layout(G, k=1, iterations=50)
        elif layout == "circular":
            pos = nx.circular_layout(G)
        elif layout == "kamada_kawai":
            pos = nx.kamada_kawai_layout(G)
        elif layout == "shell":
            pos = nx.shell_layout(G)
        else:
            pos = nx.spring_layout(G)
        
        # Color nodes by type/cluster if available
        node_colors = []
        color_map = defaultdict(lambda: len(color_map))
        colors = ['lightblue', 'lightgreen', 'lightcoral', 'lightyellow', 'lightpink', 
                 'lightgray', 'lightcyan', 'lavender', 'wheat', 'lightsteelblue']
        
        if hasattr(graph, 'entity_clusters') and graph.entity_clusters:
            for node in G.nodes():
                cluster = graph.entity_clusters.get(node, 'default')
                color_idx = color_map[cluster] % len(colors)
                node_colors.append(colors[color_idx])
        else:
            # Simple coloring based on node name patterns
            for node in G.nodes():
                if 'Researcher' in node:
                    node_colors.append('lightcoral')
                elif 'Suggestion' in node:
                    node_colors.append('lightgreen')
                elif any(word in node.lower() for word in ['neutrino', 'physics', 'hypothesis']):
                    node_colors.append('lightblue')
                elif any(word in node.lower() for word in ['machine', 'learning', 'model']):
                    node_colors.append('lightyellow')
                else:
                    node_colors.append('lightgray')
        
        # Draw nodes
        nx.draw_networkx_nodes(G, pos, node_color=node_colors, 
                              node_size=1000, alpha=0.7)
        
        # Draw edges
        nx.draw_networkx_edges(G, pos, edge_color='gray', 
                              arrows=True, arrowsize=20, alpha=0.6)
        
        # Draw labels for nodes
        nx.draw_networkx_labels(G, pos, font_size=8, font_weight='bold')
        
        # Draw edge labels (relations)
        edge_labels = nx.get_edge_attributes(G, 'label')
        nx.draw_networkx_edge_labels(G, pos, edge_labels, font_size=6)
        
        # Create legend
        legend_elements = [
            mpatches.Patch(color='lightcoral', label='Researchers'),
            mpatches.Patch(color='lightgreen', label='Suggestions'),
            mpatches.Patch(color='lightblue', label='Physics/Neutrino'),
            mpatches.Patch(color='lightyellow', label='ML/Models'),
            mpatches.Patch(color='lightgray', label='Other')
        ]
        plt.legend(handles=legend_elements, loc='upper right')
        
        plt.title("Knowledge Graph Visualization", fontsize=16, fontweight='bold')
        plt.axis('off')
        plt.tight_layout()
        
        # Save if path provided
        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"Graph saved to: {save_path}")
        
        plt.show()
        
        # Print statistics
        print(f"\nGraph Statistics:")
        print(f"Nodes (Entities): {len(entities)}")
        print(f"Edges (Relations): {len(relations)}")
        print(f"Edge Types: {len(graph.edges) if hasattr(graph, 'edges') else 'N/A'}")
        
        # Print most connected entities
        if len(G.nodes()) > 0:
            degree_centrality = nx.degree_centrality(G)
            top_entities = sorted(degree_centrality.items(), key=lambda x: x[1], reverse=True)[:5]
            print(f"\nMost Connected Entities:")
            for entity, centrality in top_entities:
                print(f"  {entity}: {centrality:.3f}")
    
    def save_graph_data(self, graph: dict, filepath):
        """
        Save graph data to a JSON file for later analysis.
        
        Args:
            graph: The Graph object returned by self.kg.generate()
            filepath: Path to save the JSON file
        """
        import json
        
        graph_data = {
            "entities": list(graph.entities) if hasattr(graph, 'entities') else [],
            "edges": list(graph.edges) if hasattr(graph, 'edges') else [],
            "relations": list(graph.relations) if hasattr(graph, 'relations') else [],
            "entity_clusters": graph.entity_clusters if hasattr(graph, 'entity_clusters') else None,
            "edge_clusters": graph.edge_clusters if hasattr(graph, 'edge_clusters') else None
        }
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(graph_data, f, indent=2, ensure_ascii=False)
        
        print(f"Graph data saved to: {filepath}")


if __name__ == "__main__":
    kg_gen = KG_Generator()
    # extract_scientific_content = kg._extract_scientific_content(sample_1)
    extracted_scientific_content = kg_gen.generate(sample_1)
    print(extracted_scientific_content)
    
    # Visualize the generated knowledge graph
    print("\nGenerating visualization...")
    for reseracher, graph in extracted_scientific_content.items():
        kg_gen.visualize_graph(graph) 
    # kg_gen.visualize_graph(extract_scientific_content, layout="spring", figsize=(14, 10))
    
    # Save graph data for later analysis
    # kg_gen.save_graph_data(extract_scientific_content, "knowledge_graph_output.json")